name: Bio_explorer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bash=5.2.21=h7f99829_0
  - bash_kernel=0.10.0=pyh707e725_0
  - bedtools=2.31.1=h13024bc_3
  - bioawk=1.0=h577a1d6_13
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.14=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - curl=8.11.1=h332b0f4_0
  - debugpy=1.8.12=py313h46c70d0_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filetype=1.2.0=pyhd8ed1ab_0
  - htslib=1.21=h566b1c6_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblzma=5.6.3=hb9d3cd8_1
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h0d44e9d_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncbi-vdb=3.2.0=h9948957_0
  - ncurses=6.5=h2d0b736_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.4.0=h7b32b05_1
  - ossuuid=1.6.2=h5888daf_1001
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - perl=5.32.1=7_hd590300_perl5
  - perl-alien-build=2.84=pl5321h7b50bb2_0
  - perl-alien-libxml2=0.17=pl5321h577a1d6_1
  - perl-business-isbn=3.007=pl5321hdfd78af_0
  - perl-business-isbn-data=20210112.006=pl5321hdfd78af_0
  - perl-capture-tiny=0.48=pl5321hdfd78af_2
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-constant=1.33=pl5321hdfd78af_2
  - perl-data-dumper=2.183=pl5321hec16e2b_1
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-ffi-checklib=0.28=pl5321hdfd78af_0
  - perl-file-chdir=0.1010=pl5321hdfd78af_3
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-importer=0.026=pl5321hdfd78af_0
  - perl-mime-base64=3.16=pl5321hec16e2b_2
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-path-tiny=0.122=pl5321hdfd78af_0
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scope-guard=0.21=pl5321hdfd78af_3
  - perl-sub-info=0.002=pl5321hdfd78af_1
  - perl-term-table=0.024=pl5321hdfd78af_0
  - perl-test2-suite=0.000163=pl5321hdfd78af_0
  - perl-uri=5.12=pl5321hdfd78af_0
  - perl-xml-libxml=2.0210=pl5321hf886d80_0
  - perl-xml-namespacesupport=1.12=pl5321hdfd78af_1
  - perl-xml-sax=1.02=pl5321hdfd78af_1
  - perl-xml-sax-base=1.09=pl5321hdfd78af_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=pyh145f28c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=6.1.1=py313h536fd9c_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.13.1=ha99a958_105_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.13=5_cp313
  - pyzmq=26.2.0=py313h8e95178_3
  - readline=8.2=h8228510_1
  - samtools=1.21=h96c455f_1
  - seqtk=1.4=h577a1d6_3
  - six=1.17.0=pyhd8ed1ab_0
  - sra-tools=3.2.0=h4304569_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py313h536fd9c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/jake/miniconda3/envs/Bio_explorer
